/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation.panels;

import entityes.Book;
import exceptions.FacadeException;
import facade.AddBookFCD;
import facadeInterfaces.IAddBookFCD;
import javax.swing.JOptionPane;

/**
 *
 * @author skevi
 */
public class PnlAddBook extends javax.swing.JPanel {

    private IAddBookFCD addBookFCD;
    
    /**
     * Creates new form PnlAddBook
     */
    public PnlAddBook() {
        initComponents();
        initialConfig();
    }
    
    private void initialConfig(){
        this.addBookFCD = new AddBookFCD();
    }
    
    /**
     * Cleans the input fields of the frame
     */
    private void cleanFields(){
        this.txfISBN.setText("");
        this.txfTitle.setText("");
        this.txfAuthor.setText("");
    }

    private Book getBook(){
        String isbn = this.txfISBN.getText();
        String title = this.txfAuthor.getText();
        String author = this.txfAuthor.getText();
        
        Book book = new Book(isbn, title, author);
        return book;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfTitle = new javax.swing.JTextField();
        txfISBN = new javax.swing.JTextField();
        txfAuthor = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        txfTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txfTitle.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo"));

        txfISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txfISBN.setBorder(javax.swing.BorderFactory.createTitledBorder("ISBN"));

        txfAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txfAuthor.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setText("Agregar");
        btnAdd.setToolTipText("");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Agregar Libro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(284, 284, 284))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(txfAuthor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(txfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(txfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            
        Book book = getBook();
        
        int option = JOptionPane.showConfirmDialog(
                null, 
                "¿Esta seguro de querer agregar el libro?", 
                "Confirmación", 
                JOptionPane.YES_NO_OPTION
            );
        
        if (option == JOptionPane.YES_OPTION) {
            this.addBookFCD.addBook(book);   
            JOptionPane.showMessageDialog(null, "Libro agregado con "
                    + "exito");
        }
        
        }catch(FacadeException fe){
            JOptionPane.showMessageDialog(this, fe.getMessage(), 
                    "Error al agregar el usuario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txfAuthor;
    private javax.swing.JTextField txfISBN;
    private javax.swing.JTextField txfTitle;
    // End of variables declaration//GEN-END:variables
}
