/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation.panels;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import presentation.FrmUpdateBook;
import utilities.RoundedBorder;

/**
 *
 * @author skevi
 */
public class PnlBooks extends javax.swing.JPanel {

    /**
     * Creates new form PnlBooks
     */
    public PnlBooks() {
        initComponents();
        styles();
    }
    
    private void styles(){
        
        RoundedBorder border = new RoundedBorder(30);
        
        this.btnAddBook.setContentAreaFilled(false);
        this.btnAddBook.setBorder(border);
        
        this.btnUpdateBook.setContentAreaFilled(false);
        this.btnUpdateBook.setBorder(border);
        
        this.btnRemoveBook.setContentAreaFilled(false);
        this.btnRemoveBook.setBorder(border);
    }
    
    private void paintPanel(JPanel panel){
        panel.setSize(730, 420);
        panel.setLocation(0,0);
        
        this.removeAll();
        this.add(panel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddBook = new javax.swing.JButton();
        btnRemoveBook = new javax.swing.JButton();
        btnUpdateBook = new javax.swing.JButton();

        btnAddBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddBook.setText("Añadir Libro");
        btnAddBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnRemoveBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRemoveBook.setText("Eliminar Libro");
        btnRemoveBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBookActionPerformed(evt);
            }
        });

        btnUpdateBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateBook.setText("Actualizar Libro");
        btnUpdateBook.setToolTipText("");
        btnUpdateBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnUpdateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnRemoveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBookActionPerformed
        PnlRemoveBook remove = new PnlRemoveBook();
        
        paintPanel(remove);
    }//GEN-LAST:event_btnRemoveBookActionPerformed

    private void btnUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookActionPerformed
        FrmUpdateBook update = new FrmUpdateBook();
        
        update.setVisible(true);
    }//GEN-LAST:event_btnUpdateBookActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        PnlAddBook add = new PnlAddBook();
        
        paintPanel(add);
    }//GEN-LAST:event_btnAddBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnRemoveBook;
    private javax.swing.JButton btnUpdateBook;
    // End of variables declaration//GEN-END:variables
}
