/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation.panels;

import dao.BookDAO;
import dao.LoanDAO;
import dao.UserDAO;
import daoInterfaces.IBookDAO;
import daoInterfaces.ILoanDAO;
import entityes.Book;
import entityes.Loan;
import entityes.User;
import exceptions.DAOException;
import exceptions.FacadeException;
import facade.ReturnBookFCD;
import facadeInterfaces.IReturnBookFCD;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author skevi
 */
public class PnlReturnBook extends javax.swing.JPanel {

    private static IReturnBookFCD returnBookFCD;
    private static IBookDAO bookDAO;
    private static ILoanDAO loanDAO;
    private static UserDAO userDAO;

    /**
     * Creates new form PnlLendBook
     */
    public PnlReturnBook() {
        initComponents();
        bookDAO = new BookDAO();
        loanDAO = new LoanDAO();
        userDAO = new UserDAO();

        returnBookFCD = new ReturnBookFCD(bookDAO, loanDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        txfISBN = new javax.swing.JTextField();
        txfID = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Regresar Libro");

        btnReturn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReturn.setText("Regresar");
        btnReturn.setToolTipText("");
        btnReturn.setAlignmentX(0.5F);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        txfISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txfISBN.setBorder(javax.swing.BorderFactory.createTitledBorder("ISBN"));
        txfISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfISBNActionPerformed(evt);
            }
        });

        txfID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txfID.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        txfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfID, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)))
                .addGap(59, 59, 59)
                .addComponent(btnReturn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnReturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addComponent(txfID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void regresarLibro() throws FacadeException, DAOException {
        try {
            Book book = bookDAO.searchByISBN(txfISBN.getText());
            User user = userDAO.getByID(Integer.parseInt(txfID.getText()));

            Loan prestamo = loanDAO.searchByBookAndUser(book, user);

            returnBookFCD.returnBook(prestamo);

        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Error al regresar el libro.", JOptionPane.ERROR_MESSAGE);
        }

    }


    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed

        int option = JOptionPane.showConfirmDialog(
                null,
                "¿Esta seguro de querer regresar el libro?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
        );

        try {
            if (option == JOptionPane.YES_OPTION) {
                regresarLibro();
                JOptionPane.showMessageDialog(null, "Libro regresado con exito");

            }
        } catch (FacadeException ex) {
            Logger.getLogger(PnlReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DAOException ex) {
            Logger.getLogger(PnlReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }

        clearFields();
    }//GEN-LAST:event_btnReturnActionPerformed
    private void clearFields() {
        this.txfISBN.setText("");
        this.txfID.setText("");
    }
    private void txfISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfISBNActionPerformed

    private void txfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txfID;
    private javax.swing.JTextField txfISBN;
    // End of variables declaration//GEN-END:variables
}
