package presentation.panels;

import dao.BookDAO;
import dao.LoanDAO;
import dao.UserDAO;
import daoInterfaces.IBookDAO;
import daoInterfaces.ILoanDAO;
import entityes.Book;
import entityes.Loan;
import entityes.User;
import exceptions.DAOException;
import exceptions.FacadeException;
import facade.ReturnBookFCD;
import facadeInterfaces.IReturnBookFCD;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author skevi
 */
public class PnlReturnBook extends javax.swing.JPanel {

    private static IReturnBookFCD returnBookFCD;
    private static IBookDAO bookDAO;
    private static ILoanDAO loanDAO;
    private static UserDAO userDAO;

    /**
     * Creates new form PnlLendBook
     */
    public PnlReturnBook() {
        initComponents();
        bookDAO = new BookDAO();
        loanDAO = new LoanDAO();
        userDAO = new UserDAO();

        returnBookFCD = new ReturnBookFCD(bookDAO, loanDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        txfISBN = new javax.swing.JTextField();
        txfID = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Regresar Libro");

        btnReturn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReturn.setText("Regresar");
        btnReturn.setToolTipText("");
        btnReturn.setAlignmentX(0.5F);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        txfISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txfISBN.setText("000-0-000");
        txfISBN.setToolTipText("");
        txfISBN.setBorder(javax.swing.BorderFactory.createTitledBorder("ISBN"));
        txfISBN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfISBNFocusGained(evt);
            }
        });
        txfISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfISBNActionPerformed(evt);
            }
        });

        txfID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txfID.setText("ID");
        txfID.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        txfID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfIDFocusGained(evt);
            }
        });
        txfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfID, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(txfISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(txfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txfID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnReturn)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void regresarLibro() throws FacadeException, DAOException {
        try {
            Book book = bookDAO.searchByISBN(txfISBN.getText());
            User user = userDAO.getByID(Integer.parseInt(txfID.getText()));

            Loan prestamo = loanDAO.searchByBookAndUser(book, user);

            returnBookFCD.returnBook(prestamo);

        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Error al regresar el libro.", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed

        int option = JOptionPane.showConfirmDialog(
                null,
                "¿Esta seguro de querer regresar el libro?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
        );

        try {
            if (option == JOptionPane.YES_OPTION) {
                regresarLibro();
                JOptionPane.showMessageDialog(null, "Libro regresado con exito");

            }
        } catch (FacadeException ex) {
            Logger.getLogger(PnlReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DAOException ex) {
            Logger.getLogger(PnlReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }

        clearFields();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void clearFields() {
        this.txfISBN.setText("");
        this.txfID.setText("");
    }

    private void txfISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfISBNActionPerformed

    private void txfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfIDActionPerformed

    private void txfIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfIDFocusGained
        txfID.setText("");
    }//GEN-LAST:event_txfIDFocusGained

    private void txfISBNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfISBNFocusGained
        txfISBN.setText("");
    }//GEN-LAST:event_txfISBNFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txfID;
    private javax.swing.JTextField txfISBN;
    // End of variables declaration//GEN-END:variables
}
